language: python
sudo: required
services:
  - postgresql
  - redis
  - docker
python: "2.7"
install:
  - bash bin/travis-build.bash
  - pip install coveralls
  - pip freeze
script: sh bin/travis-run.sh
after_success:
  - coveralls